export const GET_ALL_CHAPTERS = "GET_ALL_CHAPTERS"
export const ADD_NEW_CHAPTER= "ADD_NEW_CHAPTER"



export const GET_CHAPTER_BY_ID = "GET_CHAPTER_BY_ID"


export const GET_CHAPTER_CONTENT_BY_ID = "GET_CHAPTER_CONTENT_BY_ID"


export const GET_CONTENTS = "GET_CONTENTS";



